var options = {
  solution: 			[[null,	null,	null,	null,	null,	null,	null,	null,	null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                           [null,	null,	null,	null,	null,	null,	null,	null,	null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                           [null,	null,	null,	null,	null,	null,	null,	null,	null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                           [null,	null,	null,	 'A',	 'Q',	 'U',	 'A',	 'P',	 'H',    'O',    'B',    'I',    'C',   null,   null,   null,   null,   null,   null,   null],
                           [null,	null,	null,	null,	null,	null,	null,	null,	null,    'C',   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                           [null,	null,	null,	 'T',	 'I',	 'T',	 'A',	 'N',	 'I',    'C',   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                           [null,	null,	null,	null,	null,	null,	null,	null,	null,    'A',   null,   null,   null,   null,    'B',   null,   null,   null,   null,   null],
                           [null,	null,	null,	null,	null,	 'P',	null,	null,	null,    'S',   null,   null,   null,    'G',    'U',    'Y',   null,   null,   null,   null],
                           [null,	null,	null,	null,	null,	 'L',	null,	null,	null,    'I',   null,   null,    'F',   null,    'R',   null,   null,   null,   null,   null],
                           [null,	null,	null,	 'E',	 'L',	 'E',	 'C',	 'T',	 'R',    'O',   null,   null,    'O',   null,    'S',   null,   null,   null,   null,   null],
                           [null,	null,	null,	null,	null,	 'A',	null,	null,	null,    'N',    'U',    'G',    'G',    'E',    'T',   null,   null,   null,   null,   null],
                           [null,	null,	null,	null,	 'A',	 'S',	 'K',	 'E',	 'D',   null,   null,    'A',   null,    'A',   null,   null,   null,   null,   null,   null],
                           [null,	null,	null,	null,	null,	 'E',	null,	null,	null,   null,   null,    'P',   null,    'S',   null,   null,   null,   null,   null,   null],
                           [null,	null,	null,	null,	null,	null,	null,	null,	null,   null,   null,    'I',   null,    'Y',   null,   null,   null,   null,   null,   null],
                           [null,	null,	null,	null,	null,	null,	null,	null,	null,   null,   null,    'N',   null,   null,   null,   null,   null,   null,   null,   null],
                           [null,	null,	null,	null,	null,	 'E',	 'A',	 'R',	 'R',    'I',    'N',    'G',    'E',    'D',   null,   null,   null,   null,   null,   null],
                           [null,	null,	null,	null,	null,	null,	null,	null,	null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                           [null,	null,	null,	null,	null,	null,	null,	null,	null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                           [null,	null,	null,	null,	null,	null,	null,	null,	null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                           [null,	null,	null,	null,	null,	null,	null,	null,	null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null]],


       index: 				[[null,  null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                           [null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                           [null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                           [null,   null,   null,      1,   null,   null,   null,   null,   null,      2,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                           [null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                           [null,   null,   null,      3,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                           [null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,     10,   null,   null,   null,   null,   null],
                           [null,   null,   null,   null,   null,      5,   null,   null,   null,   null,   null,   null,   null,      6,   null,   null,   null,   null,   null,   null],
                           [null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,      7,   null,   null,   null,   null,   null,   null,   null],
                           [null,   null,   null,    '8',   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                           [null,   null,   null,   null,   null,   null,   null,   null,   null,      9,   null,      4,   null,     11,   null,   null,   null,   null,   null,   null],
                           [null,   null,   null,   null,     12,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                           [null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                           [null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                           [null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                           [null,   null,   null,   null,   null,     13,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                           [null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                           [null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                           [null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                           [null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null]],

    questions_across: [	     "1. Fear of water",
                             "3. Ship that sank in 1912",
                             "6. The opposite of lady",
                             "8. Spider man villain",
                             "9. Breaded chicken strips",
                             "12. Past of asking",
                             "13. Who put earring is"],

    questions_down: [		    "2. I saved this wine for a special...",
                            "4. When i went back home the window was...",
                            "5. Can I drink water...",
                            "7. What is an Azawakh",
                            "10. If you pierce a balloon what does it do",
                            "11. The opposite of difficult"]

};


cwp_nmsp.activateCWP(document.getElementById("myPuzzle"),false,options);